---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base utilities
  apt:
    name:
      - net-tools          
      - curl
      - wget
      - unzip
      - gnupg
      - lsb-release
      - ca-certificates
      - software-properties-common
    state: present

