---
all:
  children:
    nyct-server:
      hosts:
        instance1:
          ansible_host: 34.44.146.28

      vars:
        ansible_user: kamzy
        ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY') }}"
